model:
  base_model_id: "microsoft/phi-3-mini-4k-instruct"
  trust_remote_code: true
  torch_dtype: "auto"
  device_map: "auto"
  use_flash_attention_2: false  # Optional, set true if supported and needed
