peft:
  mode: qlora
  task_type: "CAUSAL_LM"
  target_modules: ["qkv_proj", "o_proj", "gate_up_proj", "down_proj"]  # ✅ Valid for Phi-3
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  trainable_parts:
    train_embeddings: false
    train_output_head: true
    train_norm_layers: false

quantization:
  enabled: true
  load_in_4bit: true
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: "nf4"

train:
  output_dir: "checkpoints"
  max_steps: 100                           # Train for 100 steps
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1                      # Optional if max_steps isn't hit
  learning_rate: 2e-4                      # Learning rate for adapter layers
  eval_steps: 100                          # Evaluation and logging every 100 steps
  save_steps: 100                          # Save checkpoint every 100 steps
  save_total_limit: 2                      # Keep only 2 checkpoints
  logging_steps: 20                        # Log every 20 steps
  use_fp16: true
  use_bf16: false                           # Set based on your Colab GPU support
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.05                       # 5% warmup steps for LR scheduler
  seed: 42
  report_to: "none"                        # No W&B or other reporters
